name: calc_test

on:

  push:
    branches: [ main ]


  workflow_dispatch:


jobs:  
        
   build:
   
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Run and check
        run: python main.py
        
      - name: Create exe file
        run: python -m py_compile main.py > main.exe
        
      - name: Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Commit exe file
        run: |
            git add main.exe
            git commit -a -m 'Changes pushed by GitHub Actions' || true
            git push origin main
            
      - name: Run tests
        run: python -m unittest test_calc.py
